コンテナのprofileが存在しない場合, エラーメッセージに表示させる
KeioAIConsortium/jupyterhub-lxd-spawner pull request #8
Opened 2020-08-17 06:53 UTC by yuziroppe

# WHAT

profileが存在しない場合

```container profile: jupyterhub-singleuser-testee does not exist```

のようなエラーメッセージをjournalctlのログで表示

2020-08-17 11:27 UTC, 190ikp commented
@mt-caret 
ひとつ思ったんだけど，これってなんでbase imageのほうでprofile指定せずにユーザコンテナ作成時にプロファイル指定するようにしてるんだっけ？
jupyterhub-singleuserイメージのほうでそもそもprofileを指定しておけば必要ない気がするけど...(今はdefaultになってる)

2020-08-18 05:08 UTC, mt-caret commented on lxdspawner/spawner.py
> +        if subprocess.run(['lxc', 'profile', 'show', container_profile]).returncode == 1:
これpylxdで実現する方法なかった感じ？

2020-08-18 05:12 UTC, mt-caret commented
@190ikp 
> ひとつ思ったんだけど，これってなんでbase imageのほうでprofile指定せずにユーザコンテナ作成時にプロファイル指定するようにしてるんだっけ？
> jupyterhub-singleuserイメージのほうでそもそもprofileを指定しておけば必要ない気がするけど...(今はdefaultになってる)
base imageにprofileって指定できるんだっけ？元々作った時そういう風にしたくてやろうとした気がするんだけどコンテナからimageをpublishした時点でプロファイルは別に引き継がれなくてこういう風にしたんだよね。

2020-08-18 05:24 UTC, yuziroppe commented on lxdspawner/spawner.py
> +        if subprocess.run(['lxc', 'profile', 'show', container_profile]).returncode == 1:
今確認したところ, pylxd.Client().profile.exists(profile_name)とかでできそうだったので代替します

2020-08-18 06:04 UTC, yuziroppe commented
修正を加えました. よろしくお願いしまーす.

2020-08-18 06:20 UTC, mt-caret requested changes

2020-08-18 06:20 UTC, mt-caret commented on lxdspawner/spawner.py
> +                           self.container_profile)
Falseによる判定、微妙な気がする
ログをチェック箇所に持っていって例外投げてもよさそう

2020-08-18 06:22 UTC, mt-caret commented
@yuziroppe 
あとはプロファイルがちゃんと存在するかの同様のチェックをai_roomのjupyterhub_config.pyに記載しても良さそう
本来はspawnerでチェックするべきだと思うけど軽く調べた感じだとJupyterHub起動時のフックってspawnerのAPIに用意されてないようだし

2020-08-22 13:02 UTC, yapatta commented on lxdspawner/spawner.py
> +                           self.container_profile)
旅行していて返信が遅くなってしまいました. 来週着手します.

2020-08-22 13:09 UTC, yapatta commented on lxdspawner/spawner.py
> +                           self.container_profile)
このログがclass LXDSpawner内でしか出せないのでstartの帰り値の値に応じてエラーログを出すように書いてしまいましたが,確かに例外を投げてそれを249行目のstartでcatchして, エラーメッセージをログで表示みたいにするのが良さそうでした.

2020-08-22 14:05 UTC, mt-caret commented on lxdspawner/spawner.py
> +                           self.container_profile)
> このログがclass LXDSpawner内でしか出せないのでstartの帰り値の値に応じてエラーログを出すように書いてしまいました

なるほど、そういうことか。確かにfunctionalに書いている関係でちょっと扱いにくい感じになっているね。そういう話だったアプローチは２つありそう:

- functionalにいく: ログを関数内から出せるように`self.log`を関数に渡してしまう
- OOPでいく: 関数をLXDSpawnerのメソッドにする

そんなコード量があるわけでもないしどっちでも可読性はそんなに変わらないだろから（OOPスタイルの方が若干綺麗かな？）どっちのアプローチでも良さそう

2020-08-26 13:42 UTC, yuziroppe commented
functionalに修正を加えました, よろしくおねがいします

2020-08-27 01:52 UTC, mt-caret commented
該当するプロファイルが存在しない時点でJupyterHubを起動しているのはおかしいから、コンフィグでチェックをしてなかったら例外を投げて落ちるようにする、って感じかな

2020-08-27 01:57 UTC, mt-caret approved these changes

2020-08-27 05:17 UTC, yuziroppe commented
了解しました, これをマージしてai_roomの方でissueを立てて自分にアサインしておきます

2020-08-27 05:31 UTC, merged